// Code Generated by Sidekick is for learning and experimentation purposes only.
import { Component, OnInit } from '@angular/core';
import { product } from '../data-type';
import { ProductService } from '../services/product.service';

@Component({
  selector: 'app-home',
  templateUrl: './home.component.html',
  styleUrls: ['./home.component.css'],
})
export class HomeComponent implements OnInit {
  popularProducts: product[] = [];
  popularProductChunks: product[][] = [];
  trendyProducts: product[] = [];

  constructor(private productService: ProductService) {}

  ngOnInit(): void {
    this.productService.popularProducts().subscribe((data) => {
      this.popularProducts = data || [];
      this.popularProductChunks = this.chunkProducts(this.popularProducts, 4);
    });

    this.productService.trendyProducts().subscribe((data) => {
      this.trendyProducts = data || [];
    });
  }

  chunkProducts(products: product[], chunkSize: number): product[][] {
    const result = [];
    for (let i = 0; i < products.length; i += chunkSize) {
      result.push(products.slice(i, i + chunkSize));
    }
    return result;
  }
}
